WHen we combine multiple series it become dataframe

In [1]:
import numpy as np
import pandas as pd

## Creating a Data-frame

In [3]:
#creating DF from a DICT
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
#creating Df from a LIST
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
col_name=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=col_name)

In [13]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

SELECTION AND INDEXING OF COLUMNS

In [14]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [15]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

CREATING A NEW COLOUMN

In [16]:
df2["Dsignation"]=["Doctor","Eng.","Pilot","Chef"]

In [17]:
df2

    Name  Age      City  Salary Dsignation
0   John   28  New York   65000     Doctor
1   Anna   34     Paris   70000       Eng.
2  Peter   29    Berlin   62000      Pilot
3  Linda   42    London   85000       Chef

REMOVING A COLOUMN

In [ ]:
#axis =0 #vertical axis 
#axis =1 #horizontal axis
"""
      Columns →
      A   B   C
Rows ↓
0
1
2
"""
#df.drop will not delete our coloumn permanently it will just show the temporary look 
#for permanent delete we have to use df.drop(["Salary",axis=1,inplace=true])
df2.drop("Salary",axis=1,inplace=True)
# for multiple delete just use list  df.drop(["name","age"],axis=1,inplace=True)

In [22]:

df2

    Name  Age      City Dsignation
0   John   28  New York     Doctor
1   Anna   34     Paris       Eng.
2  Peter   29    Berlin      Pilot
3  Linda   42    London       Chef

SELECTING ROWS

In [23]:
df2

    Name  Age      City Dsignation
0   John   28  New York     Doctor
1   Anna   34     Paris       Eng.
2  Peter   29    Berlin      Pilot
3  Linda   42    London       Chef

In [26]:
df2.iloc[[0,1]]#loc means location and it is used to select rows

   Name  Age      City Dsignation
0  John   28  New York     Doctor
1  Anna   34     Paris       Eng.

SELECTING SUBSET OF ROWS AND COLOUMNS

In [29]:
df2.loc[[0,1]][["City","Dsignation"]]

       City Dsignation
0  New York     Doctor
1     Paris       Eng.

In [30]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

CONDITIONAL SELECTION

In [31]:
# age>30
df2[df2["Age"] > 30]

    Name  Age    City Dsignation
1   Anna   34   Paris       Eng.
3  Linda   42  London       Chef

In [33]:
#age>30 and city=paris
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City Dsignation
1  Anna   34  Paris       Eng.