In [ ]:
import numpy as np
import pandas as pd
"""
*find-->    df.isna(),df.isna().sum(),df.isna().any()
*remove---> df.dropna(thresh=3)
*filling--> df.fillna()

"""
#nothing is applying permanently to do so use (inplace=True)

Finding Missing data

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
#nan is null values
df=pd.DataFrame(data)

In [3]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [6]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
df.isna().sum()#it will sum of all null values in our data in a colomn

A    1
B    0
C    2
D    3
dtype: int64

In [7]:
df.isna().any()#check will there is null value or not

A     True
B    False
C     True
D     True
dtype: bool

REMOVING NULL VALUES

In [8]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna()#poora row delete ho jayega jisme bhi null value hoga

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(thresh=3)#agar 3 nulll values hongi toh row will be removed

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

FILLING THE MISSING DATA

In [12]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [13]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [14]:
#diff values for each coloumn
v={"A":0,"B":100,"C":233,"D":144}
df.fillna(value=v)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  144.0
2  0.0  3    3.0  144.0
3  4.0  4  233.0  144.0
4  5.0  5  233.0    5.0

In [15]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0